[project]
name = "arm-mito"
version = "0.1.0"
description = ""
authors = ["Mauro Silberberg <maurosilber@gmail.com>"]
channels = ["https://prefix.dev/conda-forge"]
platforms = ["osx-arm64"]

[dependencies]
numpy = "*"
libgfortran5 = ">=14"
pandas = "*"
pint = "*"
pint-pandas = "*"
python = ">=3.10"
scipy = "*"
symbolite = "<0.7"
tabulate = "*"
typing_extensions = "*"
narwhals = "*"
zarr = "*"

[pypi-dependencies]
arm = { path = ".", editable = true }
scipy-events = { path = "../scipy-events", editable = true }
poincare = "*"
simbio = { path = "../simbio", editable = true }

[tasks.1_variable]
cwd = "data"
cmd = "python 1_variable.py"
inputs = ["data/1_variable.py"]
outputs = ["data/1_variable.zarr"]

[tasks.2_stochastic]
cwd = "data"
cmd = "python 2_stochastic.py"
inputs = ["data/2_stochastic.py"]
outputs = ["data/2_stochastic.zarr"]

[tasks.3_mitocondria]
cwd = "data"
cmd = "python 3_mitocondria.py"
inputs = ["data/3_mitocondria.py"]
outputs = ["data/3_mitocondria.zarr"]

[feature.test.dependencies]
pytest = "*"

[feature.pysb]
channels = ["alubbock"]
dependencies = { pysb = "*" }

[feature.pysb.pypi-dependencies]
earm = { git = "https://github.com/acorbat/earm" }
caspase-model = { git = "https://github.com/acorbat/caspase_model" }

[feature.plot.dependencies]
ipykernel = ">=6.29.5"
ipywidgets = "*"
matplotlib = "*"
polars = "*"
seaborn = "*"
pyarrow = ">=17.0.0"
pint = ">=0.24.3"
pint-pandas = ">=0.6.2"
jinja2 = ">=3.1.4"
python-ternary = ">=1.0.8"

[feature.rebop]
platforms = ["osx-arm64", "linux-64"]
system-requirements = { linux = "3.10", libc = "2.17" }

[feature.rebop.tasks]
simulations = { cmd = "python runner.py", cwd = "notebooks/simbio_rebop" }
upload = { cmd = "rsync -a --progress ARM$N yoda@yoda:maurosilber/arm-mito/results", cwd = "notebooks/rebop/results" }
download = { cmd = "rsync -a --progress yoda@yoda:maurosilber/arm-mito/results/ARM$N .", cwd = "notebooks/rebop/results" }
sync = { cmd = "pixi run upload && pixi run download", cwd = "notebooks/rebop/results" }

[feature.rebop.dependencies]
xarray = "*"
pyarrow = ">=17.0.0"
tqdm = ">=4.66.5"
typer = ">=0.12.5"

[feature.rebop.pypi-dependencies]
rebop = ">=0.9"

[feature.numba.dependencies]
numba = "*"

[feature.lint.tasks]
setup = "pre-commit install"
lint = "pre-commit run"

[feature.lint.dependencies]
pre-commit = "*"
taplo = "*"
ruff = "*"
mdformat = "*"
mdformat-ruff = "*"
nbstripout = "*"

[feature.dask.dependencies]
dask = "*"

[feature.dask.pypi-dependencies]
dask-checkpoint = "*"

[environments]
lint = { features = ["lint"], no-default-feature = true }
test = ["test", "pysb"]
rebop = ["rebop"]
default = ["rebop", "plot", "numba", "test", "pysb", "dask"]
