[project]
name = "arm-mito"
version = "0.1.0"
description = "Add a short description here"
authors = ["Mauro Silberberg <maurosilber@gmail.com>"]
channels = ["conda-forge", "alubbock"]
platforms = ["osx-arm64"]

[tasks]

[dependencies]
poincare = ">=0.5.0,<0.6"
ipykernel = ">=6.29.5,<6.30"
matplotlib = ">=3.9.1,<3.10"
numba = ">=0.60.0,<0.61"
pysb = ">=1.16.0,<1.17"
pytest = ">=8.2.2,<8.3"
pre-commit = ">=3.7.1,<3.8"

[pypi-dependencies]
simbio = ">=0.4.0, <0.5"
earm = { git = "https://github.com/acorbat/earm" }
caspase-model = { git = "https://github.com/acorbat/caspase_model" }
